filter {
  mutate {
    replace => {
      "is_array" => "false"
    }
  }
  json {
    source => "message"
    array_function => "split_columns"
    target => "OCI_VCN"
    on_error => "not_json"
  }
  if [not_json] {
    mutate {
      replace => {
        "event.idm.read_only_udm.metadata.event_type" => "GENERIC_EVENT"
        "event.idm.read_only_udm.metadata.description" => "%{message}"
      }
    }
  } 
  else {
    # --- Core Metadata ---
    mutate {
      replace => {
        "event.idm.read_only_udm.metadata.vendor_name" => "OCI_VCN"
        "event.idm.read_only_udm.metadata.product_name" => "OCI_VCN"
        "event.idm.read_only_udm.metadata.log_type" => "OCI_VCN"
        "event.idm.read_only_udm.metadata.event_type" => "NETWORK_CONNECTION"
        #"event.idm.read_only_udm.metadata.event_type" => "GENERIC_EVENT"
      }
      #on_error => "err_common_fields"
    }
    mutate {
        replace => {
            "event.idm.read_only_udm.network.session_id" => "%{OCI_VCN.flowid}"
        }
        #on_error =>"err_network.session_id"
    }
    mutate {
        replace =>{
            "var1" => "%{OCI_VCN.sourceAddress}" 
        }
    }
    mutate {
        merge => {
            "event.idm.read_only_udm.principal.ip" => "var1"
        }
        #on_error =>"principal.ip"
    }
    
    mutate {
        replace =>{
            "var2" => "%{OCI_VCN.destinationAddress}"
        }
    }
    mutate {
        merge => {
            "event.idm.read_only_udm.target.ip" => "var2"
        }
        #on_error =>"target.ip"
    }
    }
    mutate {
      convert => {
    "OCI_VCN.sourcePort" => "integer"
    "OCI_VCN.destinationPort" => "integer"
  }
}
  mutate {
      rename => {
        "OCI_VCN.sourcePort" => "event.idm.read_only_udm.principal.port"
        "OCI_VCN.destinationPort" => "event.idm.read_only_udm.target.port"
      }
    }

     mutate {
      convert => {
    "OCI_VCN.bytesOut" => "integer"
  }
}
  mutate {
      rename => {
        "OCI_VCN.bytesOut" => "event.idm.read_only_udm.principal.network.sent_packets"
      }
    }

  mutate {
  replace => {
    "event.idm.read_only_udm.network.ip_protocol" => "%{OCI_VCN.protocolName}"
  }
}
mutate {
  convert => {
    "OCI_VCN.packets" => "integer"
  }
}
mutate {
  rename => {
    "OCI_VCN.packets" => "event.idm.read_only_udm.network.sent_packets"
  }
}


 if [OCI_VCN][action] == "ACCEPT" {
    
    mutate {
        replace => {
          "temp_action" => "ALLOW"
        }
    }
      mutate {
        merge => {
          "sec_result.action" => "temp_action"
        }
      }
    } else {
      if [OCI_VCN][action] == "REJECT" {
       
       mutate {
        replace => {
          "temp_action" => "ALLOW"
        }
    }
        mutate {
          merge => {
            "sec_result.action" => "temp_action"
          }
    
        }
      }
    }
mutate {
          merge => {
            "event.idm.read_only_udm.security_result" => "sec_result"
          }
        }

    mutate {
      convert => {
        "OCI_VCN.startTime" => "string"
        "OCI_VCN.endTime" => "string"
      }
    }
       
    date {
      match => ["OCI_VCN.startTime", "UNIX"]
      target => "event.idm.read_only_udm.metadata.event_timestamp"
    }

    
  mutate {
    merge => {
      "@output" => "event"
    }
  }
}